name = "kale-addresses"

# [[tables]]
# name = "balances"
# force = true

# [[tables.columns]]
# name = "address"
# col_type = "BYTEA"
# index = true

# [[tables.columns]]
# name = "balance"
# col_type = "BIGINT"